### ISSUE TITLE
Set the version by an action

### ISSUE THREAD

**Issue by iBrotNano** [iBrotNano/TestEnvironment#1]
# [Set the version by an action #1](https://github.com/iBrotNano/TestEnvironment/issues/1)

## TODOs

- [x] Generate version numbers
- [x] The replacement expression needs the xml tags to work
- [x] Where does the spaces came from after the version numbers in Directory.Build.props
- [x] Change the version number placeholders in the project files
- [x] https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- [x] Check if the version is set in all project files and the README.md
- [x] Version number in README.md is not set

**Comment by iBrotNano** [comment]
I will check the version number in the README.md and in the compiled binaries to ensure, that everything works.

**Comment by iBrotNano** [comment]
I have to change set-output into another method. https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
