### ISSUE TITLE
Configure source link

### ISSUE THREAD

**Issue by iBrotNano** [iBrotNano/TestEnvironment#10]
### Open Questions?

-

### Blockers

-

### Description

Configuring source link for the project.

### Conditions

The sources must be public on GitHub.

### Side effects

-

## Acceptance tests

- [x] I will check in the NuGet if source link is configured by opening the NuGet.

## Design

SourceLink can be configured with a NuGet. It must be added as a dependency and the rest should work by itself.

https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink describes this configuration.

## Dissection

| Integration test | 1                                          |
| --------------- | ------------------------------------------- |
| Action          | Check the NuGet in the NuGet Explorer. Proof that the hook by SourceLink is checked. |
| Expected result | The hook is checked.                     |

### TODOs

- [x] Create a `feature` branch if needed (Maybe configuration changes or new project files)
- [x] Update the dependencies
- [x] Add a SourceLink NuGet
- [x] Check if the exception handling is well done
- [x] Check if further tests must be written
- [x] Write meaningful comments
- [x] Are there any compiler warnings?
- [x] Do all unit tests pass?
- [x] Is the version number correctly configured?
- [x] Phrase a meaningful commit comment
- [x] Check-in the changes and push them to the server

### Notes

-

## Debug

| ID   | Result | Pass |
| ---- | ------ | ---- |
| 1   | SourceLink is configured. | 🟢 |

## Documentation

- [x] Do I need a new PIA or update an existing one? 🔴
- [x] Update the README.md
- [x] Update the CHANGELOG.md
- [x] Describe the setup of the story if needed for end users
- [x] Does something in the wiki needed to be updated?
- [x] Needs other stuff been documented?

### Decisions

-

### PIAs

-

### Links

- [Any other documentation should be linked here. Intern and extern.](https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)

## Demo

- [x] Setup a fresh demo environment

The NuGet shows that SourceLink is configured.

## Deployment

- [x] Merge `feature` into `master` with a `squash` and remove the `feature` branch
- [x] Check if the compiled artifact is valid
- [x] Cleanup the Git history locally on the dev system
