### ISSUE TITLE
Cache dependencies in the build to increase performance

### ISSUE THREAD

**Issue by iBrotNano** [iBrotNano/TestEnvironment#14]
### Open Questions?

1. @Who: What must be discussed?

### Blockers

1. Something blocks my work.

### Description

Caching is a feature in GitHub Actions to increase build performance by caching stuff during a build and reusing it in another build. I will create a cache for the NuGets.

### Conditions

-

### Side effects

-

## Acceptance tests

1. The build will work without errors. A test build will be done to ensure this.
2. Caching is used in a second build. I will proof the logs to ensure this.

## Design

How can the task be done?

## Dissection

| Integration test | ID                                          |
| --------------- | ------------------------------------------- |
| Action          | What has to be done to validate the system? |
| Expected result | What is a valid result?                     |

### TODOs

- [ ] Create a `feature` branch if needed (Maybe configuration changes or new project files)
- [ ] Update the dependencies
- [ ] Here is the place for development todo items
- [ ] Check if the exception handling is well done
- [ ] Check if further tests must be written
- [ ] Write meaningful comments
- [ ] Are there any compiler warnings?
- [ ] Do all unit tests pass?
- [ ] Is the version number correctly configured?
- [ ] Phrase a meaningful commit comment
- [ ] Check-in the changes and push them to the server

### Notes

Notes about the development of the issue.

## Debug

| ID   | Result | Pass |
| ---- | ------ | ---- |
| 1   |        | 🟢🔴🟡  |

## Documentation

- [ ] Do I need a new PIA or update an existing one?
- [ ] Update the README.md
- [ ] Update the CHANGELOG.md
- [ ] Describe the setup of the story if needed for end users
- [ ] Does something in the wiki needed to be updated?
- [ ] Needs other stuff been documented?

### Decisions

| Decision          | Description                |
| ----------------- | -------------------------- |
| What was decided? | Why was the decision made? |

### PIAs

Link to related PIA

### Links

- [ ] Any other documentation should be linked here. Intern and extern.

## Demo

- [ ] Setup a fresh demo environment

Results of the acceptance tests.

## Deployment

- [ ] Merge `feature` into `master`  with a `squash` and remove the `feature` branch
- [ ] Check if the compiled artifact is valid
- [ ] Cleanup the Git history locally on the dev system
