### ISSUE TITLE
Add a test project and write tests for all code

### ISSUE THREAD

**Issue by iBrotNano** [iBrotNano/TestEnvironment#15]
### Open Questions?

1. @Who: What must be discussed?

### Blockers

1. Something blocks my work.

### Description

A project about testing should be tested by itself. I should create a test project and use the TestEnvironment to write tests for itself. It will ensure the quality of the code itself and show that the project is working.

### Input

Test data will be used which is defined and created by the developer.

### Output

The system will create test results and matrices. They can be used to ensure the quality of the code.

### Conditions

-

### Side effects

-

## Acceptance tests

1. First test to validate the requirement.
1. Second test.

## Design

Architecture of the system and/or layout of the GUI. Specification of the input and output data.

## Dissection

| Integration test | ID                                          |
| --------------- | ------------------------------------------- |
| Action          | What has to be done to validate the system? |
| Expected result | What is a valid result?                     |

### TODOs

- [ ] Create a `feature` branch
- [ ] Update the dependencies
- [ ] Here is the place for development to-do items
- [ ] Check if the exception handling is well done
- [ ] Check if further tests must be written
- [ ] Write meaningful comments
- [ ] Are there any compiler warnings?
- [ ] Do all unit tests pass?
- [ ] Is the version number correctly configured?
- [ ] Phrase a meaningful commit comment
- [ ] Check-in the changes and push them to the server

### Notes

Notes about the development of the issue.

## Debug

| ID   | Result | Pass |
| ---- | ------ | ---- |
| 1   |        | 🟢🔴🟡  |

## Documentation

- [ ] Do I need a new PIA or update an existing one?
- [ ] Update the README.md
- [ ] Update the CHANGELOG.md
- [ ] Describe the setup of the story if needed for end users
- [ ] Does something in the wiki needed to be updated?
- [ ] Needs other stuff been documented?

### Decisions

| Decision          | Description                |
| ----------------- | -------------------------- |
| What was decided? | Why was the decision made? |

### PIAs

Link to related PIA

### Links

- [ ]  Any other documentation should be linked here. Intern and extern.

## Demo

- [ ] Setup a fresh demo environment

Results of the acceptance tests.

## Deployment

- [ ] Merge `feature` into `master`  with a `squash` and remove the `feature` branch
- [ ] Check if the compiled artifact is valid
- [ ] Cleanup the Git history locally on the dev system
