### ISSUE TITLE
Add issue templates to the repo

### ISSUE THREAD

**Issue by iBrotNano** [iBrotNano/TestEnvironment#2]
# Details

## TODO

- [x] How can i add templates to the project?
- [x] Write a template for a task
- [x] Write a template for a release
- [x] Add my template to the project
- [x] Adding a template chooser (https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)
- [x] Add meta information to the templates
- [x] The title must not be part of the content
- [x] ID of a test must not have a sharp
- [x] Headline of the task template must be capital
- [x] Is there a way to generate markdown from a yaml form? (no)
- [x] Can i configure what templates can be used by users?
- [x] Add templates for end users
- [x] Fix the templates
- [x] Change the description of the templates to inform what types are used for end users

## Design

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository describes how to add templates for issues.

## Dissection

1. All template types must work. I will create a test issue with all of them.
2. The fields must work

## Acceptance tests

- [x] I want to ensure that i can add issues with the newly added templates by creating test issues.
