### ISSUE TITLE
Make the project honor all third party licenses

### ISSUE THREAD

**Issue by iBrotNano** [iBrotNano/TestEnvironment#24]
### Open Questions?

1. @Who: What must be discussed?

### Blockers

- [x] `dotnet-project-licenses` does not execute on the build server

### Description

I will have to check what licenses the projects are using on which my project depends. I guess i will need at least a file to list all those dependencies with their licenses.

### Conditions

-

### Side effects

I will have to check if all licenses' conditions are met.

## Acceptance tests

- [x] All dependencies are listed with their license.
- [x] All conditions of those licenses are met.
- [x] The project templates are modified by a task to check the licenses and their conditions for new dependencies.
- [x] The project template is synchronized with the GitLab template.

## Design

- [x] How can I handle open-source licence conditions correctly?
- [x] List all Licenses of all dependencies
- [x] Check those licenses for conditions to met

I should check all licenses of used NuGets when i use them. I should modify my checklists to have a reminder. 

There is a tool i can use to generate a file containing license information for all used NuGets mentioned in [Get license information for all used NuGet packages in .NET Core outside of Visual Studio](https://stackoverflow.com/questions/55470771/get-license-information-for-all-used-nuget-packages-in-net-core-outside-of-visu). The tool must be used in the 3.0.0-alpha version to support `Directory.Packages.props`.  [Nuget License Utility](https://github.com/tomchavakis/nuget-license) documents the usage. With this tool I can generate a license matrix as a file and add it to the file `LICENSE` of my project. This will be added to the NuGet as a file.

In the PowerShell the command looks like this:

```powershell
dotnet-project-licenses -i .\MarcelMelzig.TestEnvironment.sln >> .\LICENSE
```

There should be an equivalent for bash on the build server. 

## Dissection

| Integration test | 1 |
| --------------- | ------------------------------------------- |
| Action          | I will check that all GitHub issue templates have a TODO to check the licenses for newly added dependencies. |
| Expected result | All issue templates have such a TODO.                     |

| Integration test | 2 |
| --------------- | ------------------------------------------- |
| Action          | I will check that all GitLab issue templates have a TODO to check the licenses for newly added dependencies. |
| Expected result | All issue templates have such a TODO.                     |

| Integration test | 3 |
| --------------- | ------------------------------------------- |
| Action          | I will check that the licence matrix is in the build NuGet. |
| Expected result | The license matrix is part of the LICENSE in the NuGet. |

### TODOs

- [x] Create a `feature` branch if needed (Maybe configuration changes or new project files)
- [x] Update the dependencies
- [x] Remove deprecated packages
- [x] Is it possible to add `README.md` and `LICENSE` to `Directory.Build.props`?
- [x] Modify the GitHub templates for licence checks
- [x] Modify the GitLab templates for license checks
- [x] Modify the template for `Directory.Build.props` to include a file `LICENSE`
- [x] `dotnet-project-licenses` does not execute on the build server
- [x] The output is not appended to LICENSE except the first one
- [x] Export the licenses in a file `Third Party Licenses`
- [x] Add `Third Party Licenses` to the NuGet
- [x] Add the generation of the LICENSE to the pipeline
- [x] Check the licenses for supported ones
- [x] Update the template for `Directory.Build.props` to add THIRD-PARTY-NOTICE.TXT and THX
- [x] Check if the exception handling is well done
- [x] Check if further tests must be written
- [x] Write meaningful comments
- [x] Are there any compiler warnings?
- [x] Do all unit tests pass?
- [x] Is the version number correctly configured?
- [x] Phrase a meaningful commit comment
- [x] Check-in the changes and push them to the server

### Notes

⚠Warning
There were some deprecated dependencies in the project. I could remove the by referencing a framework. https://learn.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#framework-reference

✖ Error
`dotnet-project-licenses` did not work in a pipeline. So, i had to choose another tool. https://github.com/pleonex/ThirdLicense

ℹ Info
I uploaded my license and the third party notice doing https://github.com/actions/upload-artifact#upload-using-multiple-paths-and-exclusions.

## Debug

- [x] 1: 🟢 Result: As Expected
- [x] 2: 🟢 Result: As Expected
- [x] 3: 🟢 Result: As Expected

## Documentation

- [x] Do I need a new PIA or update an existing one?
- [x] Update the README.md
- [x] Update the CHANGELOG.md
- [x] Describe the setup of the story if needed for end users
- [x] Does something in the wiki needed to be updated?
- [x] Needs other stuff been documented?

### Decisions

| Decision          | Cause                      |
| ----------------- | -------------------------- |
| I changed the tool to generate a Third Party Notice file into https://github.com/pleonex/ThirdLicense. | The originally planned tool did not work in a pipeline for some reason. The export of the new tool is much better. |

### PIAs

-

### Links

- [Get license information for all used NuGet packages in .NET Core outside of Visual Studio](https://stackoverflow.com/questions/55470771/get-license-information-for-all-used-nuget-packages-in-net-core-outside-of-visu)
- [dotnet-project-licenses](https://www.nuget.org/packages/dotnet-project-licenses/3.0.0-alpha.9)
- [Nuget License Utility](https://github.com/tomchavakis/nuget-license)
- [Framework reference](https://learn.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#framework-reference)
- [Third License](https://github.com/pleonex/ThirdLicense)
- [Upload using Multiple Paths and Exclusions](https://github.com/actions/upload-artifact#upload-using-multiple-paths-and-exclusions)

## Demo

- [x] Setup a fresh demo environment

Results of the acceptance tests.

## Deployment

- [ ] Merge `feature` into `master` with a `squash` and remove the `feature` branch
- [ ] Check if the compiled artifact is valid
- [ ] Cleanup the Git history locally on the dev system
