### ISSUE TITLE
Tag the version of a build by an action

### ISSUE THREAD

**Issue by iBrotNano** [iBrotNano/TestEnvironment#3]
## Design

I will tag the current commit with the current package version number. I will use [pkgdeps/git-tag-action](https://github.com/pkgdeps/git-tag-action) to tag the version.

***

**Note**

The action can be found in the marketplace under https://github.com/marketplace/actions/pkgdeps-git-tag-action.

***

## TODO

- [x] Is there a plugin for this task?
- [x] Modify the permissions to enable tagging
- [x] Tag the current commit with the build package number

## Acceptance tests

- [x]  After a build is done by an action i will check if the package version is used as a tag in Git

## Notes

The GitHub token must have the correct permissions.

***

**Note**

https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

***
