### ISSUE TITLE
Configure SourceLink with DotNet.ReproducibleBuilds

### ISSUE THREAD

**Issue by iBrotNano** [iBrotNano/TestEnvironment#38]
### Open Questions?

1. @Who: What must be discussed?

### Blockers

1. Something blocks my work.

### Description

DotNet.ReproducibleBuilds is a package which encapsulates the configuration of SourceLink and deterministic builds in a single NuGet. It could be a standard for the configuration and keep track with changes in the configuration just by updating the package.

https://github.com/dotnet/reproducible-builds is the project page.

### Conditions

Buildserver builds must produce deterministic builds. Local builds must be debugable.

### Side effects

🔴

## Acceptance tests

1. I will check with the NuGet Package Explorer that SourceLink is enabled for builds done by the GitHub action.
2. I will check with the NuGet Package Explorer that the package is deterministic for builds done by the GitHub action.
3. I will check that debugging works locally in Visual Studio.

## Design

How can the task be done?

## Dissection

| Integration test | ID                                          |
| --------------- | ------------------------------------------- |
| Action          | What has to be done to validate the system? |
| Expected result | What is a valid result?                     |

### TODOs

- [ ] Create a `feature` branch if needed (Maybe configuration changes or new project files)
- [ ] Update the dependencies
- [ ] Here is the place for development todo items
- [ ] Check if the exception handling is well done
- [ ] Check if further tests must be written
- [ ] Write meaningful comments
- [ ] Are there any compiler warnings?
- [ ] Do all unit tests pass?
- [ ] Is the version number correctly configured?
- [ ] Phrase a meaningful commit comment
- [ ] Check-in the changes and push them to the server

### Notes

Notes about the development of the issue.

## Debug

| ID   | Result | Pass |
| ---- | ------ | ---- |
| 1   |        | 🟢🔴🟡  |

## Documentation

- [ ] Do I need a new PIA or update an existing one?
- [ ] Update the README.md
- [ ] Update the CHANGELOG.md
- [ ] Describe the setup of the story if needed for end users
- [ ] Does something in the wiki needed to be updated?
- [ ] Needs other stuff been documented?

### Decisions

| Decision          | Cause                      |
| ----------------- | -------------------------- |
| What was decided? | Why was the decision made? |

### PIAs

Link to related PIA

### Links

- [Any other documentation should be linked here. Intern and extern.](https://github.com/dotnet/reproducible-builds)

## Demo

- [ ] Setup a fresh demo environment

Results of the acceptance tests.

## Deployment

- [ ] Merge `feature` into `master` with a `squash` and remove the `feature` branch
- [ ] Check if the compiled artifact is valid
- [ ] Cleanup the Git history locally on the dev system
