### ISSUE TITLE
Release 1.0.5

### ISSUE THREAD

**Issue by iBrotNano** [iBrotNano/TestEnvironment#5]
## Details

| Name      | Value |
| :-------- | :---- |
| Milestone | [1.0.5](https://github.com/iBrotNano/TestEnvironment/milestone/1) |
| Owner     | @iBrotNano  |

### Todo

- [x] Create a `release` branch from `master` for the RC
- [x] Release branches must be build
- [x] What looks the generated version number like?
- [x] Fix the version number
- [x] Start the test phase
- [x] Collect all test results
- [x] Create bugfix issues if needed for the current release
- [x] Start bugfixing
- [x] Redo the test phase
- [x] Update the version number for the release (Major.Minor.Patch)
- [x] There is already a nuget on nuget.org with this version number
- [x] Rename milestone 1.0.5 into 1.0.6
- [x] Rename milestone 1.0.6 into 1.0.7
- [x] Merge `release`  into `master` and `production` with `fast forward`
- [x] Tag `production` with version number from current milestone
- [x] Update the Changelog in the wiki
- [x] Close the milestone

### Notes

The generated version number is: `Package version is 1.0.5-release/1.0.5-109`. This is not valid.

The version 1.0.5 is already published. I will iterate the version to 1.0.6 and rename the milestone 1.0.6 to 1.0.7.
