### ISSUE TITLE
Create DbContexts for reals databases used in integration tests

### ISSUE THREAD

**Issue by iBrotNano** [iBrotNano/TestEnvironment#59]
### Description

Creating a `DbContext` of a real database could be useful for integration tests. Those tests should be separated from unit tests.

### Open Questions?

1. @Who: What must be discussed?

### Blockers

1. Something blocks my work.

### Input

What data goes into the system and what is their source?

### Output

What data goes out of the system and why?

### Conditions

What conditions must be met? High pressure? Many users?

### Side effects

Are there any?

## Acceptance tests

- [ ] First test to validate the requirement.
- [ ] Second test.

## Design

Architecture of the system and/or layout of the GUI. Specification of the input and output data.

## Dissection

| Integration test | ID                                          |
| --------------- | ------------------------------------------- |
| Action          | What has to be done to validate the system? |
| Expected result | What is a valid result?                     |

### TODOs

- [ ] Create a `feature` branch
- [ ] Update the dependencies
- [ ] Document the updated dependencies in CHANGELOG.md
- [ ] Here is the place for development to-do items
- [ ] Check if the exception handling is well done
- [ ] Check if further tests must be written
- [ ] Write meaningful comments
- [ ] Are there any compiler warnings?
- [ ] Do all unit tests pass?
- [ ] Is the version number correctly configured?
- [ ] Phrase a meaningful commit comment
- [ ] Check-in the changes and push them to the server

### Notes

Notes about the development of the issue.

## Debug

| ID   | Result | Pass |
| ---- | ------ | ---- |
| 1   |        | 🟢🔴🟡  |

## Documentation

- [ ] Do I need a new PIA or update an existing one?
- [ ] Update the README.md
- [ ] Update the CHANGELOG.md
- [ ] Describe the setup of the story if needed for end users
- [ ] Does something in the wiki needed to be updated?
- [ ] Needs other stuff been documented?

### Decisions

| Decision          | Cause                      |
| ----------------- | -------------------------- |
| What was decided? | Why was the decision made? |

### PIAs

Link to related PIA

### Links

- Any other documentation should be linked here. Intern and extern.

## Demo

- [ ] Setup a fresh demo environment
- [ ] Check all acceptance tests

## Deployment

- [ ] Merge `feature` into `master` with a `squash` and remove the `feature` branch
- [ ] Check if the compiled artifact is valid
- [ ] Cleanup the Git history locally on the dev system
