### ISSUE TITLE
Activate the dependency graph and use it in a review process before a release

### ISSUE THREAD

**Issue by iBrotNano** [iBrotNano/TestEnvironment#67]
### Description

[Managing the dependency graph](https://docs.github.com/en/code-security/getting-started/securing-your-repository#managing-the-dependency-graph) describes how these settings can be activated. After done this i can use this information in my review process. I should make TODOs in my checklist at a suitable point.

> **Note**
> [Managing dependency review](https://docs.github.com/en/code-security/getting-started/securing-your-repository#managing-dependency-review) shows how to make a review of the dependencies.

### Open Questions?

1. @Who: What must be discussed?

### Blockers

1. Something blocks my work.

### Conditions

Reviewers must have access to this information.

### Side effects

No

## Acceptance tests

- [ ] I will check that the feature is activated in GitHub for the repository.
- [ ] I will check that TODOs are part of the review process of a release.

## Design

How can the task be done?

## Dissection

| Integration test | ID                                          |
| --------------- | ------------------------------------------- |
| Action          | What has to be done to validate the system? |
| Expected result | What is a valid result?                     |

### TODOs

- [ ] Create a `feature` branch if needed (Maybe configuration changes or new project files)
- [ ] Update the dependencies
- [ ] Document the updated dependencies in CHANGELOG.md
- [ ] Here is the place for development todo items
- [ ] Check if the exception handling is well done
- [ ] Check if further tests must be written
- [ ] Are there license conflicts for new dependencies?
- [ ] Exisits a `global.json`
- [ ] Are all TODOs in the code done?
- [ ] Write meaningful comments
- [ ] Are there any compiler warnings?
- [ ] Do all unit tests pass in Visual Studio?
- [ ] Do all unit tests pass with `dotnet test`?
- [ ] `dotnet format Contracts.Service.sln --verify-no-changes --verbosity diagnostic`
- [ ] Is the version number correctly configured?
- [ ] Phrase a meaningful commit comment
- [ ] Check-in the changes and push them to the server
- [ ] Does the build on the buildserver succeed?
- [ ] Create a PR

### Notes

Notes about the development of the issue.

> **Note**
> This is a note

> **Warning**
> This is a warning

## Debug

- [ ] ID: 🟢🔴🟡 Result: As Expected

## Documentation

- [ ] Do I need a new PIA or update an existing one?
- [ ] Update the README.md
- [ ] Update the CHANGELOG.md
- [ ] Describe the setup of the story if needed for end users
- [ ] Does something in the wiki needed to be updated?
- [ ] Needs other stuff been documented?

### Decisions

| Decision          | Cause                      |
| ----------------- | -------------------------- |
| What was decided? | Why was the decision made? |

### PIAs

Link to related PIA

### Links

- Any other documentation should be linked here. Intern and extern.

## Demo

- [ ] Setup a fresh demo environment
- [ ] Check all acceptance tests

## Deployment

- [ ] Merge `feature` into `master` or `hotfix` into `production` and `master` and remove the `bugfix` branch
- [ ] Check if the compiled artifact is valid
- [ ] Cleanup the Git history locally on the dev system
