### ISSUE TITLE
Base class for intergation tests using a database

### ISSUE THREAD

**Issue by iBrotNano** [iBrotNano/TestEnvironment#69]
### Description

As a developer i want to write integration tests using a real database to test database specific features and behaviour. Fakes often don't implement those features and cannot show if a production system might work or not. For this task I want to setup a container with the used database and run my test against this instance. I want to test operations which touch the database and migrations.

Integration tests come with their own challenges. The database in particular is a representation of a state.

1. setup of the test environment requires more effort than unit tests.
2. the state of the database should not and often cannot be shared between tests, as they are not deterministic. A test must not overwrite the test data of another test while it is being executed.
3. the state must be clearly defined before a test so that it can be meaningfully evaluated after the test.
4. tests require more resources and take longer to execute.

The test environment is implemented with [Testcontainers](https://testcontainers.com/guides/introducing-testcontainers/). This library can be used to configure the test environment in the code. It starts, configures and removes the containers during the test run.

> [!NOTE]  
> [Welcome to Testcontainers for .NET!](https://dotnet.testcontainers.org/) shows an example of a configuration for .NET.

To separate the state of the database for each test, two conditions must be met.

1. the tests may only write synchronously, not asynchronously, to the same database.
2. before each test, it must be ensured that the database is in a clean defined state for the test.

> [!NOTE]  
> [Strategies for isolating the database in tests](https://lostechies.com/jimmybogard/2013/06/18/strategies-for-isolating-the-database-in-tests/) describes solution strategies for isolating databases in tests.

`ICollectionFixture<T>`s can be used to separate read from write tests. This xUnit mechanism ensures that the tests are executed synchronously within a collection and that a fixture is initialized once for each collection. Read test just need only one fixture of test data while write tests needs a fixture per test.

[Respawn](https://github.com/jbogard/Respawn) can empty a database and thus create a clean state before a test.

> [!NOTE]  
> As the initialization performs asynchronous code calls, the xUnit interface [XUnit - Async lifetime](https://bartwullems.blogspot.com/2019/09/xunit-async-lifetime.html) is implemented.

> Don't write integration tests for every permutation of data and file access with databases and file systems. Regardless of how many places across an app interact with databases and file systems, a focused set of read, write, update, and delete integration tests are usually capable of adequately testing database and file system components. Use unit tests for routine tests of method logic that interact with these components.
>
> ~Source:~ ~https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-8.0#introduction-to-integration-tests~

Execution time, effort in defining suitable test data and resource consumption during execution mean that the number of integration tests must be limited to the essential aspects. These are the CRUD operations of a 'repository' and the possible 'responses' of an endpoint. 

For endpoints, a single test for each of `Create`, `Read`, `Update` and `Delete` is often sufficient for the request to get through to the database. However, validation by the validator can be tested more efficiently using unit tests.

You could proceed as follows:

1. unit test suite for things like `Validator`s with permutations of test data.
2. unit test suite for `controller`s with an invalid data set to test whether the validation is carried out. Status code or mocks can be used.
3. integration test suite for 'Controller's with tests that address the database.

### Open Questions?

1. @Who: What must be discussed?

### Blockers

1. Something blocks my work.

### Input

What data goes into the system and what is their source?

### Output

What data goes out of the system and why?

### Conditions

What conditions must be met? High pressure? Many users?

### Side effects

Are there any?

## Acceptance tests

- [ ] Test to validate the requirement.

## Design

Architecture of the system and/or layout of the GUI. Specification of the input and output data.

## Dissection

| Integration test | ID                                          |
| --------------- | ------------------------------------------- |
| Action          | What has to be done to validate the system? |
| Expected result | What is a valid result?                     |

### TODOs

- [ ] Create a `feature` branch
- [ ] Update the dependencies
- [ ] Document the updated dependencies in CHANGELOG.md
- [ ] Here is the place for development to-do items
- [ ] Check if the exception handling is well done
- [ ] Check if further tests must be written
- [ ] Are there license conflicts for new dependencies?
- [ ] Exisits a `global.json`
- [ ] Remove deactivated code
- [ ] Are all TODOs in the code done?
- [ ] Write meaningful comments
- [ ] Are there any compiler warnings?
- [ ] Do all unit tests pass in Visual Studio?
- [ ] Do all unit tests pass with `dotnet test`?
- [ ] `dotnet format Contracts.Service.sln --verify-no-changes --verbosity diagnostic`
- [ ] Is the version number correctly configured?
- [ ] Phrase a meaningful commit comment
- [ ] Check-in the changes and push them to the server
- [ ] Does the build on the buildserver succeed?
- [ ] Create a PR

### Notes

Notes about the development of the issue.

> **Note**
> This is a note

> **Warning**
> This is a warning

## Debug

- [ ] ID: 🟢🔴🟡 Result: As Expected

## Documentation

- [ ] Do I need a new PIA or update an existing one?
- [ ] Update the README.md
- [ ] Update the CHANGELOG.md
- [ ] Describe the setup of the story if needed for end users
- [ ] Does something in the wiki needed to be updated?
- [ ] Needs other stuff been documented?

### Decisions

| Decision          | Cause                      |
| ----------------- | -------------------------- |
| What was decided? | Why was the decision made? |

### PIAs

Link to related PIA

### Links

- Any other documentation should be linked here. Intern and extern.

## Demo

- [ ] Setup a fresh demo environment
- [ ] Check all acceptance tests

## Deployment

- [ ] Merge `feature` into `master` or `hotfix` into `production` and `master` and remove the `bugfix` branch
- [ ] Check if the compiled artifact is valid
- [ ] Cleanup the Git history locally on the dev system
