### ISSUE TITLE
Build a deterministic build

### ISSUE THREAD

**Issue by iBrotNano** [iBrotNano/TestEnvironment#9]
### Open Questions?

1. @Who: What must be discussed?

### Blockers

1. NuGet Package Explorer shows the build not as deterministic and i can't figure out why.

### Description

A deterministic build is a build which binaries are the same regardless on which machine they are build.

https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/#deterministic-builds

### Conditions

-

### Side effects

Locally build binaries should not be build deterministic because it prevents debugging.

## Acceptance tests

- [x] I will check in the NuGet compiled by the build server if the build is deterministic

## Design

[How can the task be done?](https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/#deterministic-builds) describes how to configure the build. I will create a parameter in Directory.Build.props which can be set on the buildserver build and can be omit locally.

## Dissection

| Integration test | 1                                          |
| --------------- | ------------------------------------------- |
| Action          | Check in the NuGet if the build was deterministic.  |
| Expected result | The must be a hook checked when it is opend with the NuGet Explorer. |

### TODOs

- [x] Create a `feature` branch if needed (Maybe configuration changes or new project files)
- [x] Update the dependencies
- [x] Modify `Directory.Build.props` to enable deterministic build configuration
- [x] Check the build in IlSpy
- [x] Check with a minimal example
- [x] Check with a .NET 6.0 build
- [x] Is there any other tool to check if a NuGet is deterministic?
- [x] Proof with different version of MSBuild
- [x] Try if .NET SDK 7.0.201 can be used
- [x] The log shows that `Deterministic` is set to `false`
- [x] Analyze the log
- [x] Why is the file `Shouldly.props` part of the NuGet?
- [x] Try `<ExcludeAssets>build</ExcludeAssets>`
- [x] Why is the project build as reference assembly?
- [x] NPE does not show the deterministic builds correctly. Why?
- [x] Build the app with the flag for deterministic builds
- [x] Write meaningful comments
- [x] Are there any compiler warnings?
- [x] Do all unit tests pass?
- [x] Is the version number correctly configured?
- [x] Phrase a meaningful commit comment
- [x] Check-in the changes and push them to the server
- [x] Save the build configuration files (Directory.Build.props, Directory.Package.props, build.yml, templates, README.md, CHANGELOG.md) as a snippet in GitLab.

### Notes

I could proof that the MSBuild version has no impact on the result.

I compile the assembly as a reference assembly. No metadata of private membes is published or can be used. This way only the public API of the assembly can be used. This is a more stable way to publish assemblies and should be used as default.

https://learn.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies

## Debug

| ID   | Result | Pass |
| ---- | ------ | ---- |
| 1   | The hook to indicate a deterministic build is set.       | 🟢  |

## Documentation

- [x] Do I need a new PIA or update an existing one?
- [x] Update the README.md
- [x] Update the CHANGELOG.md
- [x] Describe the setup of the story if needed for end users
- [x] Does something in the wiki needed to be updated?
- [x] Publish the solution as a blog post

### Decisions

-

### PIAs

-

### Links

- https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/#deterministic-builds
- https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files
- https://learn.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies

## Demo

- [x] Setup a fresh demo environment

The NuGet is deterministic.

## Deployment

- [ ] Merge `feature` into `master` with a `squash` and remove the `feature` branch
- [ ] Check if the compiled artifact is valid
- [ ] Cleanup the Git history locally on the dev system
